### ISSUE TITLE
how to start and use this project

### ISSUE THREAD

**Issue by sundeep95** [joypatra/Watson-IoT-Blockchain-Demo-1483384125867#1]
Hi

I am new to blockchain concept and wanted to learn it by exploring.
Found this interesting but it do not have any details of implementing this project.
Can you please provide the details of implementing and testing it.
Thanks and regards,
sundeep

**Comment by joypatra** [comment]
Hi @sundeep95 ,
I hope your question is about the concept of IoT and Blockchain, and not about how to fork a project in github.

You may refer to the series of articles associated with this project - https://www.ibm.com/developerworks/cloud/library/cl-blockchain-for-cognitive-iot-apps-trs/index.html

Please note that the article and this codebase uses Hyperledger 0.6 SDK, whereas the latest is Hyperledger 1.0.

Best of luck,

Thanks,
Joy

**Comment by sundeep95** [comment]
Hi

Thank you for information.
But I require procedure about how to fork the project.

Thanks
Sundeep

**Comment by joypatra** [comment]
You can go through the tutorials, such as https://guides.github.com/activities/forking/

We are not offering github education. For any further question on github basics, you may be better off trying to ask those on sites like stackoverflow.com.

All the best,

Thanks,
Joy
